// <auto-generated />
namespace CorralWMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_OrdrDtl_WhsCod : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_OrdrDtl_WhsCod));
        
        string IMigrationMetadata.Id
        {
            get { return "201606191924319_added_OrdrDtl_WhsCod"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
