// <auto-generated />
namespace CorralWMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedWhsInv_User : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedWhsInv_User));
        
        string IMigrationMetadata.Id
        {
            get { return "201605191533460_addedWhsInv_User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
