// <auto-generated />
namespace CorralWMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fixed_RolesUsers_Relationship : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixed_RolesUsers_Relationship));
        
        string IMigrationMetadata.Id
        {
            get { return "201604072304104_fixed_RolesUsers_Relationship"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
