// <auto-generated />
namespace CorralWMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedUsers_Roles_Permissions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedUsers_Roles_Permissions));
        
        string IMigrationMetadata.Id
        {
            get { return "201604072006193_addedUsers_Roles_Permissions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
